name: Trigger auto deployment for my-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/my-container-app-AutoDeployTrigger-592c5e3c-2e23-486e-aae5-8dcec8aac318.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MYCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: jhamlacr03.azurecr.io
          registryUsername: ${{ secrets.MYCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: my-container-app
          resourceGroup: rg-my-container-apps
          imageToBuild: jhamlacr03.azurecr.io/my-container-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


