name: Trigger auto deployment for my-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/my-container-app-AutoDeployTrigger-d45f7f8e-f5c4-47df-8a30-59cd2aa9090e.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Deploy via az cli
        uses: azure/CLI@v2
        with:
          azcliversion: 2.61.0
          inlineScript: |
            az extension add --name containerapp --upgrade --allow-preview true --only-show-errors
            az provider register --namespace Microsoft.App --only-show-errors

      - name:  Build and deploy Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: jhamlacr03
          containerAppName: my-container-app
          resourceGroup: rg-my-container-apps
          acrUsername: jhamlacr03
          acrPassword: dqZxIhol0+MmNMY3J7IqK0+1Cl0Wc90lzyesjl8nef+ACRAmrB5f
        
          
            

     

