name: Trigger auto deployment for my-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/my-container-app-AutoDeployTrigger-d45f7f8e-f5c4-47df-8a30-59cd2aa9090e.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Deploy via az cli
        uses: azure/CLI@v2
        with:
          azcliversion: 2.61.0
          inlineScript: |
            az extension add --name containerapp --upgrade --allow-preview true --only-show-errors
            az containerapp update \
                --resource-group rg-my-container-apps \
                --name my-container-app \
                --container-name my-container-app \
                --image jhamlacr03.azurecr.io/github-action/container-app:latest \
                --only-show-errors
       

        
          
            

     

